### PR TITLE
Update version to 1.0.0, update recipe

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
Should we merge this before the compile upgrade rebuild continues after the r-base work is done? So that this version is already used during rebuild then? 

There are some changes though https://cran.r-project.org/web/packages/Rcpp/news.html

Newer packages coming in are already requesting newer rcpp versions https://github.com/conda-forge/staged-recipes/pull/6750

**Comment by cbrueffer** [comment]
Seems OK to merge. The API changes don't look too bad, although there may be some fallout.

**Comment by cbrueffer** [comment]
The `r-base` update has just been committed, so the official rebuild should happen come soon. In that light I guess we may as well wait.

**Comment by dbast** [comment]
Commit is done, but not fully build yet ;)

This is also already at 0.12.19, which one version prior to this 1.0.0 https://github.com/AnacondaRecipes/r-rcpp-feedstock/blob/master/recipe/meta.yaml

I am fine either way.

**Comment by cbrueffer** [comment]
Oh, true, forgot that the rebuild doesn't actually update anything. I also didn't realize you're not on the maintainer list yet :-)

**Comment by dbast** [comment]
Thanks!

**Pull request merged**
